---
abstract: 'Predict new dates from a set of dates'
author:
  - 'Brian Hann <brian.hann+dtp@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Event-Predict
no_index:
  directory:
    - inc
    - research
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
